// Generated by https://quicktype.io

export interface IUserCreated {
  data: Data
  object: string
  type:
    | 'user.created' //active
    | 'user.updated' //disabled
    | 'user.deleted' //disabled
}

export interface Data {
  birthday: string
  created_at: number
  email_addresses: EmailAddress[]
  external_accounts: ExternalAccount[]
  external_id: null
  first_name: string
  gender: string
  id: string
  last_name: string
  last_sign_in_at: null
  object: string
  password_enabled: boolean
  phone_numbers: any[]
  primary_email_address_id: string
  primary_phone_number_id: null
  primary_web3_wallet_id: null
  private_metadata: Metadata
  profile_image_url: string
  public_metadata: Metadata
  two_factor_enabled: boolean
  unsafe_metadata: Metadata
  updated_at: number
  username: null
  web3_wallets: any[]
}

export interface EmailAddress {
  email_address: string
  id: string
  linked_to: LinkedTo[]
  object: string
  verification: EmailAddressVerification
}

export interface LinkedTo {
  id: string
  type: string
}

export interface EmailAddressVerification {
  status: string
  strategy: string
}

export interface ExternalAccount {
  approved_scopes: string
  email_address: string
  family_name: string
  given_name: string
  google_id: string
  id: string
  label: null
  object: string
  picture: string
  public_metadata: Metadata
  username: null
  verification: ExternalAccountVerification
}

export interface Metadata {}

export interface ExternalAccountVerification {
  expire_at: number
  status: string
  strategy: string
}
