name: deploy-to-vercel
on:
  pull_request:
    branches:
      - main

jobs: 
  prisma-deploy:
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: postgresql://postgres:TVDg31CCIIrwQas73mBv@containers-us-west-37.railway.app:7853/railway
    steps:
      - uses: actions/checkout@v2
      - run: npx prisma migrate deploy
        
        