name: deploy-to-vercel
on:
  pull_request:
    branches:
      - main

jobs: 
  vercel-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ">=14.x"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 

      - name: install dependencies
        run: yarn install

      - name: build
        run: yarn build
      