name: deploy-to-vercel
on:
  pull_request:
    branches:
      - main

jobs: 
  prisma-deploy:
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: postgresql://postgres:LicFm5bEaqKQAdiH@db.ivvktztsrqbjuivdletj.supabase.co:5432/postgres
    steps:
      - uses: actions/checkout@v2
      - run: npx prisma generate
      # - run: npx prisma migrate deploy
      - run: npx prisma db push
        
        